site_name: TChannel Node
repo_url: https://github.com/uber/tchannel-node

pages:
- Home: README.md
- TChannel: channel.md
- Sub Channels: sub-channels.md
- Hyperbahn: hyperbahn.md
- As Thrift: as-thrift.md
# - Specification: protocol.md
# - HTTP over TChannel: http.md
# - JSON over TChannel:  json.md
# - Thrift over TChannel: thrift.md
# - Circui/t Breaking: circuit-breaking.md
# - Traffic Metrics: metrics.md
# - Go Guide: go-guide.md
# - Node Guide: node-guide.md
# - Python Guide: python-guide.md
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: 
  - admonition:
